#!/usr/bin/env python3
"""
Encoder/Decoder fuzzing campaign for xpost's PostScript filters.

Independent reference (oracle) encoders in python (hex/a85/rle/flate) plus gs for
LZW give trusted encoded streams. xpost is exercised in four modes:

  T1 decode-correctness : oracle-encode V -> xpost DECODE -> must equal V
  T2 encode-correctness : xpost ENCODE V -> oracle DECODE -> must equal V
  T3 round-trip         : xpost ENCODE V -> xpost DECODE -> must equal V
  T4 fresh-filter EOD   : concat[ enc(V1)..enc(Vk) ][SENTINEL];  xpost reads each
                          Vi with a FRESH `currentfile /F filter` (bounded to
                          len(Vi)); the trailing SENTINEL must survive intact.
                          This is the generalised catcher for the "decoder does
                          not consume its EOD -> next fresh filter desyncs" class
                          (the dvips/colorimage bug).

All binary data flows through scratch files so arbitrary bytes are never embedded
in a PostScript program.  Requires xpost --no-sandbox (disk file access).

Usage (from the build tree):
    S=/tmp/fuzz XP=build/src/bin/xpost python3 tools/filter_fuzz.py [Filter...]
where S is a scratch directory and XP the built interpreter; with no filter
arguments it runs every filter plus the SubFileDecode checks.  ghostscript ('gs')
is used as the independent LZW oracle-encoder.  Exit status is non-zero on any
failure.  The reduced, self-contained regression subset lives in
tests/filter_eod_test.ps (generated by tools/gen_filter_eod_test.py).
"""
import os, sys, subprocess, zlib, base64, random, struct

S    = os.environ["S"]                       # scratch dir
XP   = os.environ.get("XP", "build/src/bin/xpost")
ENV  = dict(os.environ, XPOST_DATA_DIR=os.path.abspath("data"),
            LD_LIBRARY_PATH="build/src/lib")
GS   = "gs"

# ---------------------------------------------------------------- oracle encoders
def enc_hex(d):                       # ASCIIHexEncode
    return d.hex().encode() + b">"

def enc_a85(d, zfold=False):          # ASCII85Encode
    out = base64.a85encode(d)         # no 'z', no EOD
    if zfold:
        out = out.replace(b"!!!!!", b"z")   # only valid for full zero groups
    return out + b"~>"

def enc_rle(d):                       # RunLengthEncode (with repeat detection)
    out = bytearray(); i = 0; n = len(d)
    while i < n:
        # count a run of the same byte
        run = 1
        while i + run < n and d[i+run] == d[i] and run < 128:
            run += 1
        if run >= 2:
            out.append(257 - run); out.append(d[i]); i += run
        else:
            # gather a literal run until a >=3 repeat or 128 cap
            j = i; lit = bytearray()
            while j < n and len(lit) < 128:
                if j + 2 < n and d[j] == d[j+1] == d[j+2]:
                    break
                lit.append(d[j]); j += 1
            out.append(len(lit) - 1); out += lit; i = j
    out.append(128)                   # EOD
    return bytes(out)

def enc_flate(d, level=6):            # FlateEncode (zlib)
    return zlib.compress(d, level)

def enc_lzw_gs(d):                    # LZWEncode via ghostscript
    inb = os.path.join(S, "lzin.bin"); open(inb, "wb").write(d)
    prog = ("/i (%s)(r)file def /o (%%stdout)(w)file def "
            "/f o /LZWEncode filter def "
            "{ i read { f exch write } { exit } ifelse } loop "
            "f closefile o flushfile quit" % inb)
    r = subprocess.run([GS,"-q","-dNOSAFER","-dBATCH","-dNODISPLAY","-c",prog],
                       capture_output=True)
    return r.stdout

# reference DECODERS (for T2 encode-correctness, independent of xpost)
def dec_hex(d):
    s = bytes(c for c in d if c not in b" \t\r\n")
    s = s.split(b">")[0]
    if len(s) % 2: s += b"0"
    return bytes.fromhex(s.decode())
def dec_a85(d):
    body = d.split(b"~>")[0]
    return base64.a85decode(body)
def dec_rle(d):
    out = bytearray(); i = 0
    while i < len(d):
        n = d[i]; i += 1
        if n == 128: break
        if n < 128:
            out += d[i:i+n+1]; i += n+1
        else:
            out += bytes([d[i]]) * (257-n); i += 1
    return bytes(out)
def dec_flate(d): return zlib.decompress(d)
def dec_lzw_gs(d):
    inb = os.path.join(S,"lzdin.bin"); open(inb,"wb").write(d)
    prog = ("/i (%s)(r)file def /d i /LZWDecode filter def /o (%%stdout)(w)file def "
            "/s 65535 string def { d s readstring not {exit} if } loop "
            "o exch writestring o flushfile quit" % inb)
    r = subprocess.run([GS,"-q","-dNOSAFER","-dBATCH","-dNODISPLAY","-c",prog],
                       capture_output=True)
    return r.stdout

FILTERS = {
    "ASCIIHex":  dict(enc=enc_hex,      dec=dec_hex,      xenc="ASCIIHexEncode",  xdec="ASCIIHexDecode"),
    "ASCII85":   dict(enc=enc_a85,      dec=dec_a85,      xenc="ASCII85Encode",   xdec="ASCII85Decode"),
    "RunLength": dict(enc=enc_rle,      dec=dec_rle,      xenc="RunLengthEncode", xdec="RunLengthDecode"),
    "Flate":     dict(enc=enc_flate,    dec=dec_flate,    xenc="FlateEncode",     xdec="FlateDecode"),
    "LZW":       dict(enc=enc_lzw_gs,   dec=dec_lzw_gs,   xenc="LZWEncode",       xdec="LZWDecode"),
}

# ---------------------------------------------------------------- corpus
def corpus():
    rnd = random.Random(0xF12E)
    sizes = [0,1,2,3,4,5,6,7,8,15,16,63,64,65,127,128,129,255,256,257,
             511,512,513,1023,1024,1025,4095,4096,4097,8191,8192,8193,20011]
    V = []
    def add(name,b): V.append((name,b))
    for n in sizes:
        add(f"zero:{n}",   bytes(n))
        add(f"ff:{n}",     bytes([0xFF])*n)
        add(f"seq:{n}",    bytes(i & 0xFF for i in range(n)))
        add(f"rep:{n}",    (b"ABC" * (n//3 + 1))[:n])
        add(f"rand:{n}",   bytes(rnd.randrange(256) for _ in range(n)))
    # marker-heavy content: bytes that are EOD-significant for some filter
    markers = bytes([0x7e,0x3e,0x80,0x00,0x20,0x0a,0x09,0x0d,0x7a,0xff,0x21])
    for n in [4,5,8,63,64,65,127,128,129,256,4096,4097]:
        add(f"mark:{n}", bytes(markers[rnd.randrange(len(markers))] for _ in range(n)))
    # texty
    for n in [64,127,4096]:
        alpha = b"the quick brown fox 0123456789\n\t"
        add(f"text:{n}", bytes(alpha[rnd.randrange(len(alpha))] for _ in range(n)))
    return V

# ---------------------------------------------------------------- xpost runner
def run_xpost(ps):
    p = os.path.join(S,"case.ps"); open(p,"w").write(ps)
    r = subprocess.run([XP,"-q","--no-sandbox","-d","null",p],
                       stdin=subprocess.DEVNULL, capture_output=True, env=ENV, timeout=120)
    return r

def ps_copy(src_open, dst_open, filt_on_dst=None, filt_on_src=None):
    """emit PS copying every byte from an (opened) source to dest, byte at a time"""
    pass

def xpost_transform(input_bytes, direction, xfilter):
    """direction 'decode': open input, wrap /xfilter Decode, copy to out.bin.
       direction 'encode': open input, wrap out with /xfilter Encode, copy in->filter->out."""
    inb  = os.path.join(S,"tin.bin");  open(inb,"wb").write(input_bytes)
    outb = os.path.join(S,"tout.bin")
    try: os.remove(outb)
    except OSError: pass
    if direction == "decode":
        body = f"""
/i ({inb}) (r) file def
/d i /{xfilter} filter def
/o ({outb}) (w) file def
{{ d read {{ o exch write }} {{ exit }} ifelse }} loop
o closefile i closefile
"""
    else:
        body = f"""
/i ({inb}) (r) file def
/o ({outb}) (w) file def
/f o /{xfilter} filter def
{{ i read {{ f exch write }} {{ exit }} ifelse }} loop
f closefile o closefile i closefile
"""
    ps = f"{{\n{body}\n(OK\\n) print }} stopped {{ (ERR ) print $error /errorname get == }} if\n"
    r = run_xpost(ps)
    err = None
    txt = r.stdout.decode("latin1")
    if "ERR" in txt:
        err = txt.split("ERR",1)[1].strip().split("\n")[0]
    out = open(outb,"rb").read() if os.path.exists(outb) else b""
    return out, err, txt

# ---------------------------------------------------------------- test modes
def t1_decode(fname, F, V):
    fails=[]
    for name,data in V:
        try: enc = F["enc"](data)
        except Exception as e:  # oracle can't encode (shouldn't happen)
            continue
        out,err,txt = xpost_transform(enc, "decode", F["xdec"])
        if err or out != data:
            fails.append((name,len(data),"T1",err or f"got {len(out)}B want {len(data)}B",
                          enc[:32].hex(), out[:32].hex(), data[:32].hex()))
    return fails

def t2_encode(fname, F, V):
    fails=[]
    for name,data in V:
        out,err,txt = xpost_transform(data, "encode", F["xenc"])
        if err:
            fails.append((name,len(data),"T2","encode err: "+err,"","","")); continue
        try: back = F["dec"](out)
        except Exception as e:
            fails.append((name,len(data),"T2",f"oracle can't decode xpost output: {e}",
                          "", out[:32].hex(), data[:32].hex())); continue
        if back != data:
            fails.append((name,len(data),"T2",f"roundtrip via oracle mismatch got {len(back)}B",
                          "", out[:32].hex(), data[:32].hex()))
    return fails

def t3_roundtrip(fname, F, V):
    fails=[]
    for name,data in V:
        enc,err,_ = xpost_transform(data, "encode", F["xenc"])
        if err:
            fails.append((name,len(data),"T3","encode err: "+err,"","","")); continue
        out,err2,_ = xpost_transform(enc, "decode", F["xdec"])
        if err2 or out != data:
            fails.append((name,len(data),"T3",err2 or f"got {len(out)}B want {len(data)}B",
                          "", out[:32].hex(), data[:32].hex()))
    return fails

def t4_concat(fname, F, groups):
    """groups: list of lists of (name,data). Each group -> one xpost run reading
       fresh filters + trailing sentinel."""
    fails=[]
    SENT = b"<<<SENTINEL-0123456789-END>>>"
    for gi,group in enumerate(groups):
        blob = bytearray()
        for _,data in group:
            blob += F["enc"](data)
        blob += SENT
        inb  = os.path.join(S,"cin.bin");  open(inb,"wb").write(bytes(blob))
        outb = os.path.join(S,"cout.bin")
        try: os.remove(outb)
        except OSError: pass
        # PS: for each Vi, open a FRESH filter on the shared source file, read exactly
        # len(Vi) bytes via readstring, write them out with a record separator, then read
        # the sentinel raw from the underlying file and write it.
        lines = [f"/src ({inb}) (r) file def", f"/o ({outb}) (w) file def"]
        for i,(_,data) in enumerate(group):
            L=len(data)
            lines.append(f"/f{i} src /{F['xdec']} filter def")
            lines.append(f"/b{i} {max(L,1)} string def")
            if L==0:
                # nothing to read; still must let the filter consume its EOD.
                lines.append(f"f{i} read pop")  # forces a read; benign if EOF
            else:
                lines.append(f"f{i} b{i} readstring pop o exch writestring")
            lines.append("(|) print")  # progress marker to stdout (not out.bin)
        # after all filters, read remaining raw bytes (the sentinel) from src
        lines.append("/rest 200 string def")
        lines.append("src rest readstring pop o exch writestring")
        lines.append("o closefile src closefile")
        body="\n".join(lines)
        ps=f"{{\n{body}\n(OK\\n) print }} stopped {{ (ERR ) print $error /errorname get == }} if\n"
        r=run_xpost(ps)
        txt=r.stdout.decode("latin1")
        err = txt.split("ERR",1)[1].strip().split("\n")[0] if "ERR" in txt else None
        out = open(outb,"rb").read() if os.path.exists(outb) else b""
        expect = b"".join(data for _,data in group) + SENT
        if err or out != expect:
            # find first divergence per-segment
            detail=err or ""
            if not err:
                pos=0; badseg="?"
                for nm,data in group:
                    seg=out[pos:pos+len(data)]
                    if seg!=data: badseg=f"{nm}(off{pos} got {seg[:8].hex()} want {data[:8].hex()})"; break
                    pos+=len(data)
                else:
                    if out[pos:]!=SENT: badseg=f"SENTINEL corrupt: {out[pos:pos+16].hex()}"
                detail=f"desync at {badseg}"
            fails.append((f"group{gi}[{len(group)}]",len(expect),"T4",detail,"",out[:32].hex(),expect[:32].hex()))
    return fails

def t_subfile(V):
    """SubFileDecode in its normal read-until-EOD usage: `0 (EOD) SubFileDecode
    filter` passes source bytes through until it reaches the EOD string, which it
    consumes without emitting, leaving the source just past it.  A reader that
    drains the filter (oversized readstring) must get DATA, and a following raw read
    of the source must get exactly what followed the EOD.  The concat case runs a
    fresh filter per segment so each must resync the shared source."""
    fails=[]
    EOD=b"@E0D@"; SENT=b"<<SENT>>"
    picks=[(n,d) for (n,d) in V if EOD not in d and len(d)>0][:40]
    for name,data in picks:
        blob=data+EOD+SENT
        inb=os.path.join(S,"sfin.bin"); open(inb,"wb").write(blob)
        outb=os.path.join(S,"sfout.bin")
        try: os.remove(outb)
        except OSError: pass
        cap=len(data)+16
        ps=f"""{{
/src ({inb}) (r) file def
/o ({outb}) (w) file def
/d src 0 (@E0D@) /SubFileDecode filter def
/b {cap} string def
d b readstring pop o exch writestring
/rest 32 string def
src rest readstring pop o exch writestring
o closefile src closefile
(OK\\n) print }} stopped {{ (ERR ) print $error /errorname get == }} if
"""
        r=run_xpost(ps); txt=r.stdout.decode("latin1")
        err=txt.split("ERR",1)[1].strip().split("\n")[0] if "ERR" in txt else None
        out=open(outb,"rb").read() if os.path.exists(outb) else b""
        expect=data+SENT
        if err or out!=expect:
            fails.append((name,len(data),"SF",err or f"got {out[:16].hex()} want {expect[:16].hex()}","","",""))
    # fresh-filter concatenation: [D1 EOD][D2 EOD]...[SENT]; drain each, then resync
    group=picks[:8]
    blob=b"".join(d+EOD for _,d in group)+SENT
    inb=os.path.join(S,"sfcin.bin"); open(inb,"wb").write(blob)
    outb=os.path.join(S,"sfcout.bin")
    try: os.remove(outb)
    except OSError: pass
    cap=max(len(d) for _,d in group)+16
    lines=[f"/src ({inb}) (r) file def",f"/o ({outb}) (w) file def"]
    for i,(_,d) in enumerate(group):
        lines.append(f"/f{i} src 0 (@E0D@) /SubFileDecode filter def")
        lines.append(f"/b{i} {cap} string def")
        lines.append(f"f{i} b{i} readstring pop o exch writestring")
    lines.append("/rest 32 string def src rest readstring pop o exch writestring")
    lines.append("o closefile src closefile")
    ps="{\n"+"\n".join(lines)+"\n(OK\\n) print } stopped { (ERR ) print $error /errorname get == } if\n"
    r=run_xpost(ps); txt=r.stdout.decode("latin1")
    err=txt.split("ERR",1)[1].strip().split("\n")[0] if "ERR" in txt else None
    out=open(outb,"rb").read() if os.path.exists(outb) else b""
    expect=b"".join(d for _,d in group)+SENT
    if err or out!=expect:
        fails.append(("concat",len(expect),"SF-cat",err or f"got {out[:24].hex()} want {expect[:24].hex()}","","",""))
    return fails

def _run_gs_ps(prog):
    r = subprocess.run([GS,"-q","-dNOSAFER","-dBATCH","-dNODISPLAY","-c",prog],
                       capture_output=True)
    return r.stdout

def _gs_transform(input_bytes, filt, params):
    """run gs: read input file through `filt` (with params dict) to stdout"""
    inb = os.path.join(S,"gt.bin"); open(inb,"wb").write(input_bytes)
    dec = "Decode" in filt
    if dec:
        prog = ("/i (%s)(r)file def /d i %s /%s filter def /o (%%stdout)(w)file def "
                "{ d read { o exch write } { exit } ifelse } loop o flushfile quit"
                % (inb, params, filt))
    else:
        prog = ("/i (%s)(r)file def /o (%%stdout)(w)file def /f o %s /%s filter def "
                "{ i read { f exch write } { exit } ifelse } loop f closefile o flushfile quit"
                % (inb, params, filt))
    return _run_gs_ps(prog)

def _xp_transform(input_bytes, filt, params):
    """run xpost: read input file through `filt` (with params dict) to out file"""
    inb  = os.path.join(S,"xt.bin");  open(inb,"wb").write(input_bytes)
    outb = os.path.join(S,"xt.out")
    try: os.remove(outb)
    except OSError: pass
    dec = "Decode" in filt
    if dec:
        body = (f"/i ({inb}) (r) file def\n/d i {params} /{filt} filter def\n"
                f"/o ({outb}) (w) file def\n"
                "{ d read { o exch write } { exit } ifelse } loop\no closefile i closefile\n")
    else:
        body = (f"/i ({inb}) (r) file def\n/o ({outb}) (w) file def\n"
                f"/f o {params} /{filt} filter def\n"
                "{ i read { f exch write } { exit } ifelse } loop\nf closefile o closefile i closefile\n")
    ps = f"{{\n{body}\n(OK\\n) print }} stopped {{ (ERR ) print $error /errorname get == }} if\n"
    r = run_xpost(ps)
    txt = r.stdout.decode("latin1")
    err = txt.split("ERR",1)[1].strip().split("\n")[0] if "ERR" in txt else None
    out = open(outb,"rb").read() if os.path.exists(outb) else b""
    return out, err

def _bilevel(kind, cols, rows, seed=1):
    """packed 1-bit rows, cols wide (0=white in CCITT terms)"""
    stride = (cols + 7) // 8
    rnd = random.Random(seed)
    out = bytearray()
    for r in range(rows):
        row = bytearray(stride)
        for c in range(cols):
            if   kind=="white": bit=0
            elif kind=="black": bit=1
            elif kind=="vstripe": bit=c & 1
            elif kind=="hstripe": bit=r & 1
            elif kind=="edge": bit=1 if c==cols-1 else 0
            else: bit=rnd.getrandbits(1)
            if bit: row[c>>3] |= 0x80 >> (c & 7)
        out += row
    return bytes(out)

def _mask_pad(data, cols, rows):
    """zero the pad bits after Columns in each row's final byte: decoders
    (gs and xpost alike) fill them with the white background, so only the
    first Columns bits of a row are defined"""
    stride = (cols + 7) // 8
    rem = cols & 7
    if rem == 0:
        return data
    out = bytearray(data)
    mask = (0xFF00 >> rem) & 0xFF
    for r in range(rows):
        i = r * stride + stride - 1
        if i < len(out):
            out[i] &= mask
    return bytes(out)

def t_ccitt():
    """CCITTFaxDecode/Encode: G3 one-dimensional (K=0) and G4 (K<0) codings,
    gs as the independent oracle both ways, plus the xpost round trip. Rows are
    compared over their defined Columns bits only (both engines background-fill
    the final byte's padding)."""
    fails=[]
    cases=[]
    for k in (0,-1):
        for cols in (8,17,64,216,1728):
            for rows in (1,2,5):
                for kind in ("white","black","vstripe","hstripe","edge","rand"):
                    cases.append((k,cols,rows,kind))
    for k,cols,rows,kind in cases:
        data = _bilevel(kind,cols,rows)
        want = _mask_pad(data,cols,rows)
        params = f"<< /K {k} /Columns {cols} /Rows {rows} >>"
        name = f"K{k}:{cols}x{rows}:{kind}"
        genc = _gs_transform(data,"CCITTFaxEncode",params)
        # T1: gs-encode -> xpost decode
        out,err = _xp_transform(genc,"CCITTFaxDecode",params)
        if err or _mask_pad(out,cols,rows) != want:
            fails.append((name,len(data),"C-T1",err or f"got {len(out)}B want {len(data)}B","",out[:16].hex(),want[:16].hex()))
        # T2: xpost encode -> gs decode
        xenc,err = _xp_transform(data,"CCITTFaxEncode",params)
        if err:
            fails.append((name,len(data),"C-T2","encode err: "+err,"","","")); continue
        back = _gs_transform(xenc,"CCITTFaxDecode",params)
        if _mask_pad(back,cols,rows) != want:
            fails.append((name,len(data),"C-T2",f"gs can't decode xpost stream: got {len(back)}B","",back[:16].hex(),want[:16].hex()))
        # T3: xpost round trip
        out,err = _xp_transform(xenc,"CCITTFaxDecode",params)
        if err or _mask_pad(out,cols,rows) != want:
            fails.append((name,len(data),"C-T3",err or f"got {len(out)}B want {len(data)}B","",out[:16].hex(),want[:16].hex()))
    return fails, len(cases)

def _raster(kind, w, h, colors, seed=1):
    """smooth 8-bit sample rasters (DCT is lossy: content must be low-frequency)"""
    rnd = random.Random(seed)
    out = bytearray()
    for y in range(h):
        for x in range(w):
            for c in range(colors):
                if kind=="flat": v=128
                elif kind=="gradx": v=(x*255)//max(w-1,1)
                elif kind=="grady": v=(y*255)//max(h-1,1)
                else: v=min(235, 20 + x*2 + y*2 + c*15)   # gentle diagonal ramp, no wrap
                out.append(v)
    return bytes(out)

def t_dct():
    """DCTEncode/Decode: lossy, so compare per-sample within a tolerance;
    gs as the independent oracle both ways, plus the xpost round trip."""
    fails=[]; TOL=32
    cases=[(w,h,n,kind) for (w,h) in ((8,8),(16,9),(33,17))
                        for n in (1,3) for kind in ("flat","gradx","ramp")]
    def close(a,b):
        if len(a)!=len(b): return False
        return all(abs(x-y)<=TOL for x,y in zip(a,b))
    for w,h,n,kind in cases:
        data = _raster(kind,w,h,n)
        params = f"<< /Columns {w} /Rows {h} /Colors {n} >>"
        name = f"{w}x{h}c{n}:{kind}"
        genc = _gs_transform(data,"DCTEncode",params)
        # T1: gs-encode -> xpost decode
        out,err = _xp_transform(genc,"DCTDecode","<< >>")
        if err or not close(out,data):
            fails.append((name,len(data),"D-T1",err or f"mismatch got {len(out)}B want {len(data)}B","",out[:16].hex(),data[:16].hex()))
        # T2: xpost encode -> gs decode
        xenc,err = _xp_transform(data,"DCTEncode",params)
        if err:
            fails.append((name,len(data),"D-T2","encode err: "+err,"","","")); continue
        back = _gs_transform(xenc,"DCTDecode","<< >>")
        if not close(back,data):
            fails.append((name,len(data),"D-T2",f"gs decode of xpost jpeg mismatches: {len(back)}B","",back[:16].hex(),data[:16].hex()))
        # T3: xpost round trip
        out,err = _xp_transform(xenc,"DCTDecode","<< >>")
        if err or not close(out,data):
            fails.append((name,len(data),"D-T3",err or f"mismatch got {len(out)}B","",out[:16].hex(),data[:16].hex()))
    return fails, len(cases)

def make_groups(V):
    """build T4 concat groups stressing boundary-aligned segment sizes."""
    by={name:data for name,data in V}
    def pick(pfx,sizes): return [(f"{pfx}:{s}", by[f"{pfx}:{s}"]) for s in sizes if f"{pfx}:{s}" in by]
    G=[]
    # boundary-heavy sequences (the desync bites when a decode ends exactly at a
    # buffer/group/run boundary and the EOD sits just past it)
    G.append(pick("rand",[4,5,127,128,129,4095,4096,4097]))
    G.append(pick("zero",[4,64,128,4096]))
    G.append(pick("ff",[3,127,128,256]))
    G.append(pick("seq",[1,2,3,255,256,257]))
    G.append(pick("rep",[63,64,65,1024]))
    G.append(pick("mark",[4,5,64,128,4096]))
    # many tiny back-to-back (max fresh-filter churn)
    G.append([(f"seq:{s}",by[f"seq:{s}"]) for s in [1,1,1,2,2,3,3,4,5] ])
    return [g for g in G if g]

# ---------------------------------------------------------------- main
def main():
    which = sys.argv[1:] or list(FILTERS)
    V = corpus()
    groups = make_groups(V)
    total=0; allf=[]
    for fname in which:
        if fname not in FILTERS: continue
        F=FILTERS[fname]
        # LZW oracle uses gs; if a vector's gs-encode is empty (gs failed) skip it in T1/T4
        Vf=V
        if fname=="LZW":
            Vf=[(n,d) for (n,d) in V]
        f1=t1_decode(fname,F,Vf)
        f2=t2_encode(fname,F,V)
        f3=t3_roundtrip(fname,F,V)
        g = make_groups(V)
        f4=t4_concat(fname,F,g)
        n=len(f1)+len(f2)+len(f3)+len(f4)
        total+=n
        print(f"[{fname:9}] T1={len(f1):3} T2={len(f2):3} T3={len(f3):3} T4={len(f4):3}  (vectors={len(V)}, t4groups={len(g)})")
        for f in (f1+f2+f3+f4):
            allf.append((fname,)+f)
    if not sys.argv[1:] or "SubFile" in sys.argv[1:]:
        sf=t_subfile(V)
        total+=len(sf)
        print(f"[SubFile  ] SF={len(sf):3}  (positioning + fresh-filter concat)")
        for f in sf: allf.append(("SubFile",)+f)
    if not sys.argv[1:] or "CCITT" in sys.argv[1:]:
        cf,ncc=t_ccitt()
        total+=len(cf)
        print(f"[CCITT    ] C={len(cf):3}  (G3-1D + G4, gs-oracle both ways; {ncc} cases)")
        for f in cf: allf.append(("CCITT",)+f)
    if not sys.argv[1:] or "DCT" in sys.argv[1:]:
        df,ndc=t_dct()
        total+=len(df)
        print(f"[DCT      ] D={len(df):3}  (lossy round trips within tolerance; {ndc} cases)")
        for f in df: allf.append(("DCT",)+f)

    print(f"\n=== {total} failures ===")
    for f in allf[:80]:
        fn,name,ln,mode,detail,enc,out,want=f
        print(f"  {fn:9} {mode} {name:14} len={ln:<6} {detail}")
        if enc:  print(f"            enc[:32]={enc}")
        if out or want:
            print(f"            out[:32]={out}\n            want[:32]={want}")
    return 1 if total else 0

if __name__=="__main__":
    sys.exit(main())
