name: osx CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
    types: [opened, synchronize, reopened]

jobs:
  build:
    strategy:
      matrix:
        object: [small, large]
    name: osx - ${{ matrix.object }}-object
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install meson ninja fontconfig freetype libpng jpeg-turbo xcb-util xcb-util-image xcb-util-wm
    - name: configure
      run: meson setup -Dlarge-object=${{ matrix.object == 'large' }} builddir
    - name: make
      run: ninja -C builddir
    - name: meson test
      run: meson test -C builddir --print-errorlogs
